### ISSUE TITLE
Multiple publish issue

### ISSUE THREAD

**Issue by sgltkn** [cemyabansu/PublishInCrmVs2013#1]
When I selected multiple files and tried to publish them, an error occurred. Error is related to files are not open in the editor.

![error](https://cloud.githubusercontent.com/assets/7747280/9243708/9ead751a-419c-11e5-89bd-2062e5972f98.jpg)

**Comment by cemyabansu** [comment]
issue is solved. The reason is, I try to save all selected file, before sending. For saving, file must be openned in editor.
